# Generated by Django 4.0.3 on 2022-04-07 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='configs',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='round',
            name='configs',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='round',
            name='phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.phrase'),
        ),
    ]
