# Generated by Django 4.0.3 on 2022-04-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_game_configs_round_configs_alter_round_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='configs',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='round',
            name='configs',
            field=models.JSONField(default=dict),
        ),
    ]
