# Generated by Django 4.0.3 on 2022-04-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_game_configs_alter_round_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('game', 'phrase')},
        ),
    ]
